### ISSUE TITLE
Can't find asset when name starts with dot

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#70]
I am unable to obtain via a link an asset file when the name of that file starts with a dot (`.`).

See [this branch](https://github.com/TysonMN/tyson-williams-blog/tree/leanding_dot_issue).  While `codedoc serve` is running in the terminal, clicking on the link that points to `src/assets/text/.editorconfig` returns 404 in the browser and displays
```
# Not Found::
# /src/assets/text/.editorconfig
#
# tried the following paths:
# C:\Code\Blogs\tyson-williams-blog\src\assets\text\.editorconfig
# C:\Code\Blogs\tyson-williams-blog\dist\src\assets\text\.editorconfig.html
```

in the terminal.  I think this is incorrect.  I think that `C:\Code\Blogs\tyson-williams-blog\src\assets\text\.editorconfig` exists.

![2020-09-12_19-56-47_298_explorer](https://user-images.githubusercontent.com/34664007/93007774-44395780-f532-11ea-9ffc-5b26f03cb814.png)

See the file `Copy.editorconfig` in that screenshot?  I can access that file via a link that points to `src/assets/text/Copy.editorconfig`.  Therefore, I think the issue is with an asset file with a name that starts with a dot (`.`).

**Comment by loreanvictor** [comment]
yes that is the [default behavior of express static middleware](https://expressjs.com/en/4x/api.html#dotfiles), which makes sense (as the convention is for `.x` files and folders to actually be sort of hidden). so I would recommend actually not serving a file whose name starts with a dot.

**Comment by TysonMN** [comment]
I see.  Is there a compromise here?  Can I specify a list of dotfiles (as express static calls them) that don't have the default (404) behavior?  Or can I store the file on my site not as a dotfile and then change its name to not be that of a dotfile when the user downloads it?

**Comment by loreanvictor** [comment]
I would recommend first trying to see if you have the same issue on a published blog, since express is only used for development environment.

**Comment by TysonMN** [comment]
The url https://tysonwilliams.coding.blog/src/assets/text/.editorconfig returns 404.

**Comment by loreanvictor** [comment]
so we have two problems now (dev and prod). @must do you have ideas on this?

**Comment by TysonMN** [comment]
Maybe this is related to how [I have defined my assets](https://github.com/TysonMN/tyson-williams-blog/blob/feb8b07c00d429db8be9bf93027e98c55917de12/.codedoc/config.tsx#L35-L40)...
```tsx
codingBlog({
  assets: [
    'src/assets/images',
    'src/assets/favicon.ico',
  ]
}),
```

...which doesn't include the folder `src/assets/text`.  While testing locally, I had changed this to `assets: [ 'src/assets' ]`, but both settings had the same behavior accessing `src/assets/text/Copy.editorconfig` (can access for both settings) and `src/assets/text/.editorconfig` (can access for neither setting).

This local vs live/deployed issue reminds me something.  It would be great to "test" my live site without actually changing my live site.  Sort of like [blue/green deployments](https://martinfowler.com/bliki/BlueGreenDeployment.html), but it wouldn't have to be that complicated.  If I could also publish to `tysonwilliams.testing.coding.blog`, then I think that would be enough for me.

**Comment by must** [comment]
So I can provide a quick answer pending further investigation / your response. For files without a discernible MIME type (i.e. from the extension), they don't upload them to the repo. This was the result of a quick fix for files without a MIME type resulting in a failed build. But we can upload them with the MIME type "application/octet-stream" in a future fix which should resolve the issue.

**Comment by TysonMN** [comment]
> ...we can upload them with the MIME type "application/octet-stream" in a future fix which should resolve the issue.

Yes, I believe that i just verified that this would work.  When hosting locally, I verified that clicking a link that points to `src/assets/text/Copy.editorconfig` has `application/octet-stream` for the `Content-Type` in the header of the response (as seen from the development tools in Google Chrome).  That is the behavior that I also want for `src/assets/text/.editorconfig`.

**Comment by must** [comment]
It's on my todo list now. Hopefully would be done by the end of the week!

**Comment by must** [comment]
@TysonMN This change should now be live. Let me know if it works as expected.

**Comment by TysonMN** [comment]
Did you only make a change for the live site?  Will my locally hosted site continue to be unable to find an asset when the name starts with a dot?

**Comment by must** [comment]
Yeah, unfortunately, the locally served version has to be fixed separately.

**Comment by TysonMN** [comment]
> @TysonMN This change should now be live. Let me know if it works as expected.

Seems completely broken now.  Normally publishing takes just a couple minutes.  I currently have a build that won't finish successfully or with some error.  When I took this screenshot, it had been running for 13 minutes.

![2020-09-16_15-29-53_301](https://user-images.githubusercontent.com/34664007/93389423-c32fd800-f831-11ea-9736-a40ede387721.png)

> job id: aoXqrQvYACVrr3XlsIxH

**Comment by must** [comment]
Thank you for the heads up. This was an unrelated problem that prevented the cluster from scaling to accommodate new jobs. This also should be fixed now.

**Comment by TysonMN** [comment]
Yep, that deploy completed just before you made your comment.

However, that deploy still doesn't serve files my `.editorconfig` file.  Since this didn't work, I rolled back, so it is not possible to test this anymore.

![2020-09-17_07-27-53_302_chrome](https://user-images.githubusercontent.com/34664007/93470504-a211ca80-f8b7-11ea-838c-4ee5220a5093.png)

Again, maybe there is more than one issue here, and I also have to make a change to my list of assets (as I mentioned in https://github.com/CONNECT-platform/codedoc/issues/70#issuecomment-692075458).  Instead of continuing to use my actual content, I will try that using a markdown file with no in links that I only use for testing.

**Comment by must** [comment]
If I am not mistaken, your current config file doesn't include the text assets folder. Can you look into it? I have done this through my own repo and it should work: https://must.coding.blog/random/.test

**Comment by TysonMN** [comment]
Yes, you are right.  My live site is not working as desired.  Thanks!!

I think this asset configuration is another example of where local hosting and live hosting on `coding.blog` differ.  Even without including the text assets folder, I am still able to access files in that folder (that don't start with a period) when hosting locally.

**Comment by loreanvictor** [comment]
added serving dotfiles to local as well, will be deployed via `@codedoc/core@0.2.15`

**Comment by loreanvictor** [comment]
published via `@codedoc/core@0.2.15`

**Comment by TysonMN** [comment]
It nearly works.  When downloading via the link `http://localhost:3000/src/assets/text/.editorconfig`, the name of the downloaded files is `editorconfig` instead of `.editorconfig` (i.e. it is missing the leading dot).

**Comment by loreanvictor** [comment]
> It nearly works. When downloading via the link `http://localhost:3000/src/assets/text/.editorconfig`, the name of the downloaded files is`editorconfig` instead of `.editorconfig` (i.e. it is missing the leading dot).

I suppose thats express static's default behavior, I will look into its options to see if that behavior can be overridden.
